# Generated by Django 6.0.6 on 2026-06-24 08:03

import dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=dashboard.models.make_project_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('start_date', models.CharField(blank=True, max_length=20)),
                ('target_date', models.CharField(blank=True, max_length=20)),
                ('report_date', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BOQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('qty', models.FloatField(default=0)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('offer_price', models.FloatField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qty', models.FloatField(default=0)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('today_achiev', models.FloatField(default=0)),
                ('pct_today', models.FloatField(default=0)),
                ('total_present', models.FloatField(default=0)),
                ('pct_total', models.FloatField(default=0)),
                ('pct_project', models.FloatField(default=0)),
                ('target_date', models.CharField(blank=True, max_length=20)),
                ('avail_days', models.FloatField(default=0)),
                ('req_rate', models.FloatField(default=0)),
                ('req_manpower', models.FloatField(default=0)),
                ('persons_day', models.FloatField(default=0)),
                ('highlighted', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='dashboard.project')),
            ],
        ),
    ]
