# Generated by Django 6.0.6 on 2026-06-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='avg_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='ect',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
