# Generated by Django 6.0.6 on 2026-06-29 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_activity_avg_rate_activity_ect_activity_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='avail_days',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='avg_rate',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='ect',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='pct_project',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='pct_today',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='pct_total',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='persons_day',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='req_manpower',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='req_rate',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='target_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='today_achiev',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='total_present',
        ),
        migrations.AddField(
            model_name='activity',
            name='man_day_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='weight_pct',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('qty_done', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.activity')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.area')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='dashboard.project')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AreaActivityQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.activity')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='dashboard.area')),
            ],
            options={
                'unique_together': {('area', 'activity')},
            },
        ),
    ]
