# Generated by Django 6.0.6 on 2026-06-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_activity_avail_days_remove_activity_avg_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='qty',
            field=models.FloatField(default=0),
        ),
    ]
